make: compiliere_Zifferngenrator ausfuehren_des_Zifferngenrators compiliere_Algorithmus ausfuehren_des_Algorithmus	

make ziffernreihe: compiliere_Zifferngenrator ausfuehren_des_Zifferngenrators

compiliere_Zifferngenrator: 
	gcc -o Zifferngenerator.elf Zifferngenerator.c

ausfuehren_des_Zifferngenrators:
	./Zifferngenerator.elf

compiliere_Algorithmus:
	gcc -o Algorithmus.elf Algorithmus.c

ausfuehren_des_Algorithmus:
	./Algorithmus.elf
