make: compiliere_Zahlengenrator ausfuehren_des_Zahlengenrators compiliere_Algorithmus DEBUG_compiliere_algorithmus ausfuehren_des_Algorithmus
	

compiliere_Zahlengenrator: 
	gcc -o Zahlengenerator.elf Zahlengenerator.c

ausfuehren_des_Zahlengenrators:
	./Zahlengenerator.elf

compiliere_Algorithmus:
	gcc -o Algorithmus.elf Algorithmus.c

ausfuehren_des_Algorithmus:
	./Algorithmus.elf

DEBUG_compiliere_algorithmus:
	gcc -o Algorithmus.elf Algorithmus.c -DDEBUG
